### ISSUE TITLE
Update git-scripts

### ISSUE THREAD

**Issue by jihuayu** [wechaty/wechaty-puppet#103]
I used `yarn` command to install the dependencies, but it throw a error.
```text
error C:\Users\jihuayu\Documents\.sc\wechaty-puppet\node_modules\@chatie\git-scripts: Command failed.
Exit code: 127
Command: bash scripts/install.sh
Arguments:
```
I think you should update `@chatie/git-scripts` to make it can run in Windows.

Thanks

## Env

OS : Windows10
Node: v14.4.0
yarn: 1.22.4

**Comment by huan** [comment]
Good catch, thank you very much for the contribution!
