### ISSUE TITLE
Need bump wechaty-puppet version

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet#139]
This [commit](https://github.com/wechaty/wechaty-puppet/commit/2b909da169afa10016de5d236e6a332b309e24ea) has not been published success. This commit's version is `0.41.5`, but `0.41.6` has already been merged and published.

So we need to bump `wechaty-puppet` version.

**Comment by huan** [comment]
Please close this issue if your problem has been sovled.

Thank you very much.
