### ISSUE TITLE
Add params for mini-program to make the surface plot better.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet#64]
The MiniProgramPayload missed one important key named `thumbkey`.

The old `MiniProgramPayload`:
```js
export interface MiniProgramPayload {
    appid?          : string,    // optional, appid, get from wechat (mp.weixin.qq.com)
    description?    : string,    // optional, mini program title
    pagepath?       : string,    // optional, mini program page path
    thumbnailurl?   : string,    // optional, default picture, convert to thumbnail
    title?          : string,    // optional, mini program title
    username?       : string,    // original ID, get from wechat (mp.weixin.qq.com)
}
```

When we use this object to send MiniProgram, and then the surface plot is not good, so we need more attribute to improve it.

```js
thumbkey? : string,    // original, thumbnailurl and thumbkey will make the headphoto of mini-program better
```
The `thumbkey` will be needed, and use it with thumbnailurl will make MiniProgram looks better.

The demo data (**authorized by the owner**):
```
const miniProgramPayload = new MiniProgram ({
  appid: 'gh_4c1db055326c',
  title: '泰国免税店免费预约',
  pagepath: 'pages/index/index.html',
  description: '提供曼谷王权免税店、芭提雅免税店、普吉岛王权免税店和普吉岛GMS免税店的免费接送、免费送机、免费餐券和免费自助餐',
  thumbnailurl: '305d0201000456305402010002045a87e2ec02033d0af802045630feb602045dc8d38c042f6175706170706d73675f373233393165353935383839643166655f313537333434323434343130375f3232303331360204010400030201000400',
  thumbkey: 'd73ae9173a9c3a994877ee463c0dea3c',
});
```

If only use thumbnailurl like *http://xxxx.image.jpg*, it looks not so good for mini-program.

This method only supported by `wechaty-puppet-macpro`, and we can get the data of MiniProgram from message when we received a MiniProgram message.

**Comment by su-chang** [comment]
@huan Waiting for your suggestions for this issue, and then we could make MiniProgram looks better. Thank you very much.

**Comment by huan** [comment]
Sorry for the delay in responding.

I will look into this feature request this week.

**Comment by huan** [comment]
Cloud you please:

1. Explain what do you mean "not good" at "the surface plot is not good, so we need more attribute to improve it."?
1. Provide a raw payload example from the WeChat underlying protocol, so that I can review all the key names from the MiniProgram payload?

Thank you very much.

**Comment by su-chang** [comment]
If we only put url link to `thumbnailurl` without `thumbkey`, it will only show one very blur picture that we can not get any info from this picture, because `thumbnailurl` and `thumbkey` is encrypted for unzip picture. So the `thumbnailurl` in example is a string code, not a url link.

Due to the third-part api, we could only get the raw payload like the former example, no more info about MiniProgram.

P.S. We can only get `thumbnailurl` and `thumbkey` from third party api when we receive a MiniProgram message and then copy it to our MiniProgram. Otherwise we can not get the thumbkey.

**Comment by huan** [comment]
> Due to the third-part api, we could only get the raw payload like the former example, no more info about MiniProgram.

Please paste a raw payload example that sent from the native WeChat and let's have a look on it.

**Comment by su-chang** [comment]
No problem, I will share it tomorrow.

**Comment by su-chang** [comment]
The data when the bot receive a MiniProgram message:
```js
{
  my_account: 'juzi_xiaomi',
  my_name: '桔小秘22',
  my_account_alias: 'wxid_e2lc33auu61g22',
  to_account: 'Soul001001',
  to_account_alias: 'Soul001001',
  to_name: '苏畅',
  content:
   '小程序[免税店预约接送][ID:gh_4c1db055326c@app][标题:泰国免税店免费预约][描述:提供曼谷王权免税店、芭提雅免税店、普吉岛王权免税店和普吉岛GMS免税店的免费接送、免费送机、免费餐券和免费自助餐][预览图地址:3056020100044f304d02010002041092541302033d0af802044e30feb602045ddce43c0428777875706c6f61645f777869645f65326c6333336175753631673232365f313537343735373433360204010400030201000400][预览图密钥:1f7d600c7b3be809d995004805aa86e6][页面:pages/index/index.html]，请在手机端查看',
  content_type: 11,
  file_name: '',
  voice_len: '',
  type: 2,
  send_time: 1574757438,
  msgid: 5554124627149104000
}
```

**Comment by huan** [comment]
But, where is the `thumbkey`?

**Comment by su-chang** [comment]
thumb_key == 预览图密钥

**Comment by su-chang** [comment]
> But, where is the `thumbkey`?

The third party API has process the raw data to Chinese message in content.

**Comment by huan** [comment]
Please note an **UPDATE** when you update an existing reply, to make the conversation clear.

I have another question now: you said "The API params", what those params for, could you please introduce the API which can help me to understand it better?

**Comment by su-chang** [comment]
Please refresh the page, I'm editing the API params when your first comment coming.

**Comment by huan** [comment]
Sorry, I refreshed but I still can not understand.

Cloud you please reply to the issue instead of edit the original post? that will confuse lots of people including me.

Thanks.

**Comment by su-chang** [comment]
Hmmm.

The API params for send MiniProgram:
```js
{
  my_account: string, // [必须] 在聊天系统登录的微信号
  to_account: string, // [必须] 好友微信号|微信群号
  app_name: string, // [必须] 小程序的id (小程序相关参数如不清楚，可以发送小程序消息通过消息回调获取到)	例：小程序id@app
  title: string, // [必须] 小程序名称
  describe: string, // [可选] 小程序描述
  thumb_url: string, // [可选] 小程序预览图地址
  thumb_key: string, // [可选] 小程序预览图密钥
  page_path: string, // [可选] 小程序跳转页面
  type: int, //	[可选] 发送目标：1单聊，2群聊（默认1）
}
```

The `thumb_url` and `thumb_key` will make the picture of MiniProgram looks better.

But wechaty can not put `thumb_key` now.

**Comment by su-chang** [comment]
![miniprogram_img](https://user-images.githubusercontent.com/9332609/69615994-ce323580-1070-11ea-984c-5335afdc1dbe.jpeg)

**Comment by huan** [comment]
Understand. Thank you very much.

According to the raw payload, I found the name of the variable is formated well.

For example, I believe the following changes should make the variable names to be better:

```diff
export interface MiniProgramPayload {
    appid?          : string,
    description?    : string,
-     pagepath?       : string,
+     pagePath?       : string,
-    thumbnailurl?   : string,
+    thumbUrl?   : string,
    title?          : string,
    username?       : string,
-     thumbkey?       : string,
+     thumbKey?       : string,
}
```

How do you think about these changes, do you agree with me that they are necessary?

**Comment by su-chang** [comment]
Agree, it's better indeed.

**Comment by su-chang** [comment]
@huan This PR: https://github.com/wechaty/wechaty-puppet/pull/65 is waiting for your approve to make MiniProgram happy :).

**Comment by huan** [comment]
Merged.

Thank you for the effort for improving the MiniProgram system!
