### ISSUE TITLE
Make the stable wechaty-puppet-padplus have a stable wechaty-puppet dependency.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet#74]
```js

if npx --package @chatie/semver semver-is-prod $VERSION; then
  NPM_TAG=latest
else
  NPM_TAG=next
fi

npm run dist
npm run pack

TMPDIR="/tmp/npm-pack-testing.$$"
mkdir "$TMPDIR"
mv *-*.*.*.tgz "$TMPDIR"
cp tests/fixtures/smoke-testing.ts "$TMPDIR"

cd $TMPDIR
npm init -y
npm install --production \
  ...
  "wechaty-puppet@$NPM_TAG" \
  ...
```
In the travis CI, it will install wechaty-puppet@latest, but some next features are wanted  in the new version of `wechaty-puppet-padplus`. 

So we need to publish a new latest version of `wechaty-puppet`, and then it will pass the CI pack.

**Comment by huan** [comment]
Thanks for pushing the puppet version bumped!

Please feel free to send a Pull Request in the future when you need to bump the version of wechaty-puppet with a good reason.
