### ISSUE TITLE
BREAKING CHANGE v0.21: Plan to remove some exported `Interface`s

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet#85]
Today I found there have six definitions that are not used by the wechaty-puppet itself: 

1. `YOU`
1. `PuppetQRCodeScanEvent`
1. `PuppetRoomInviteEvent`
1. `PuppetRoomJoinEvent`
1. `PuppetRoomLeaveEvent`
1. `PuppetRoomTopicEvent`

The code:

https://github.com/wechaty/wechaty-puppet/blob/862137f35f94fa84a29957dc8c674ab103174360/src/schemas/puppet.ts#L3-L50

I'm planning to remove them.

There are serval puppet providers (wechaty-puppet-padplus for example) using those import, after the removal, those consumers need to copy/paste those `Interface`s to local, instead of import them from the `wechaty-puppet`.

Please let me know if there's any problems with the removal.

Thank you very much.

**Comment by huan** [comment]
@su-chang I'd like to invite you to review these breaking changes and be prepared for this breaking change.

If there's a must to keep those codes in the wechaty-puppet, please let me know ASAP.

**Comment by su-chang** [comment]
No problem with it, I will update `wechaty-puppet-padplus` when `wechaty-puppet` published new version.

**Comment by huan** [comment]
@su-chang Thank you very much for the quick confirmation!

**Comment by su-chang** [comment]
`YOU` this one has been used in puppet itself.
```js
public async roomMemberSearch (
    roomId : string,
    query  : (YOU | string) | RoomMemberQueryFilter,
)
```

So let's keep `YOU` stay in schemas? Or do some changes for `roomMemberSearch`?

**Comment by huan** [comment]
Good catch!

I'm working on that, will post at here when we have solutions.

**Comment by huan** [comment]
After re-read the code, I remembered something.

It seems that there's some reason that we should keep `YOU` in the wechaty-puppet, until we are very clear that we can remove it.

Do you agree with me that, and do you have any suggestions/comments? @su-chang

**Comment by su-chang** [comment]
Agree, `wechaty-puppet-padplus` will update later.

**Comment by huan** [comment]
Terrific.

There are also other breaking changes in the latest code of the master branch, please let me know if you have any questions.

**Comment by su-chang** [comment]
One question:
```js
public selfId (): undefined | string {
    log.verbose('Puppet', 'selfId()')

    /**
     * Huan (202003): do not throw exception. deal `undefined` outside.
     */
    // if (!this.id) {
    //   throw new Error('not logged in, no this.id yet.')
    // }

    return this.id
}
```

If we deal `undefined` outside in `selfId()`, we have to check all of them when we call this method in `wechaty-puppet-xxxx`. And `this.selfId()` as same as `thid.id`.

**Comment by huan** [comment]
Yes. Do you think that will be a problem for the puppet developers?

This change can be reverted if we have reasonable arguments.

**Comment by su-chang** [comment]
Yes, I think it is better to keep it. 

If `selfId()` return `undefine | string`, we will check it every time when we use it. In PuppetPadplus class, this method has been called 22 times in different methods.

So check one time in puppet, enjoy every time in `wechaty-puppet-xxx` is really nice.

**Comment by huan** [comment]
OK. I'll revert this change tomorrow.

Thank you for your feedback.

**Comment by huan** [comment]
Done.
