### ISSUE TITLE
How to mark the room which the bot are not in.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet#90]
When the bot has been removed from one room, but the `RoomPayload` will still store in `wechaty-puppet-padplus` cache, and it will make mistake when we find all room next time. 

So I think we need to mark these rooms.

So dose `ContactPayload`.

**Comment by huan** [comment]
What are mistakes will we make when we find all the rooms at next time? Please help me to better understand this issue by providing some examples.

Thank you very much.

**Comment by su-chang** [comment]
We will not delete room cache when the bot has been removed from the room.

If we want to send message to all rooms, we will use `bot.Room.findAll()` to get all rooms, but we can find this room which no longer belongs to the bot.

Actually, we can do nothing about this room.

**Comment by huan** [comment]
How about let's figure out whether the room is belonging to the bot by using the `room.has(bot)`?

I believe this should work if we can maintain the `memberIdList` in the room payload correctly.

And so that we can prevent introducing redundancy properties to our payload abstraction.

**Comment by su-chang** [comment]
Good idea, and how about contact?

Still use `isDeleted` attribute or create a new method?

**Question**
Now we want to add this method, do we need to make some changes on `findAll()` and `find()`, and make it easy to use?

**Comment by huan** [comment]
1. The contact is another question which I believe is not related to this issue topic (which is "how to mark the room...")
1. Answer your question: we have not added any new method. the `has()` method is an existing API already.
1. I don't think this issue is related to the `findAll()` and `find()` methods too because you can use a `filter` to filter the returned array in a very easy and clear way.

```ts
const roomList = allRoomList.filter(room => room.has(bot))
```

or use a `for` loop if we can not use `async` in the `filter`:

```ts
const roomList = []
for (const room of AllRoomList) {
  if (await room.has(bot)) {
    roomList.push(room)
  }
}
```

**Comment by su-chang** [comment]
OK, all problems have been resolved now.

Thank you very much.

**Comment by huan** [comment]
You are welcome.

**Comment by huan** [comment]
Cloud we close this issue if there's no more questions about it? Thanks!
