### ISSUE TITLE
Need new message type for Group Note message.

### ISSUE THREAD

**Issue by su-chang** [wechaty/wechaty-puppet#93]
**Example**
```
接龙
1. xxx
```

We could make it as Group Note in WeChat App, and it is a new type for wechaty.

**Comment by huan** [comment]
Glad to add the Group Note type, you are welcome to send a PR to do that.

BTW Do we have any good name for the 接龙？

**Comment by su-chang** [comment]
In English version of WeChat App, `接龙` named `GroupNote`.

**Comment by huan** [comment]
Great, the English version of the name in WeChat can be our first choice.

Thanks for the enhancement!

**Comment by su-chang** [comment]
You are welcome, happy with the new type.
